#!/bin/bash
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Not running as root"
    exit
fi

serialw=$(sed '4q;d' /etc/bind/db.matthias-friede.sb.uclllabs.be)
serial=$(echo "$serialw" | xargs)

Name=A
Regex='^(A|MX|CNAME)'

while getopts "t:" arg; do
  case $arg in
    t) 
	if [[ $OPTARG =~ $Regex ]]; then
                Name=$OPTARG
        else
        	echo "error wrong arg -t"
		exit 1
        fi
	;;
  esac
done

if [ $(( $# - $OPTIND )) -lt 1 ]; then
    echo "Usage: `basename` [options] ARG1 ARG2"
    exit 1
fi

ARG1=${@:$OPTIND:1}
ARG2=${@:$OPTIND+1:1}
ARG3=${@:$OPTIND+2:1}

serial=$((serial+1))


if [ $Name == "A" ];
then
sed -i "4s/.*/                  ${serial}/" /etc/bind/subzones/db.$ARG3
echo "$ARG1      IN      $Name           $ARG2" >> /etc/bind/subzones/db.$ARG3  

elif [ $Name == "MX" ];  
then
sed -i "4s/.*/                  ${serial}/" /etc/bind/subzones/db.$ARG3
echo "$ARG1      IN      A           $ARG2" >> /etc/bind/subzones/db.$ARG3
echo "      IN      $Name           $ARG1.$ARG3" >> /etc/bind/subzones/db.$ARG3

elif [ $Name == "CNAME" ];  
then
sed -i "4s/.*/                  ${serial}/" /etc/bind/subzones/db.matthias-friede.sb.uclllabs.be
echo "$ARG1     IN      $Name           $ARG2." >> /etc/bind/db.matthias-friede.sb.uclllabs.be
fi


systemctl restart bind9

